name: CI Pipeline for ASP.NET Core Web API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Verificar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar .NET Core SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      # 3. Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      # 4. Verificar dependencias desactualizadas
      - name: Check for outdated dependencies
        run: dotnet list package --outdated

      # 5. Ejecutar pruebas automatizadas
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      # 6. Escaneo de vulnerabilidades con CodeQL
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: 'csharp'

      # 7. Escaneo de vulnerabilidades con OWASP Dependency-Check
      - name: Install OWASP Dependency-Check
        run: |
          wget https://downloads.sourceforge.net/project/dependency-check/1.0.0.0/dependency-check-1.0.0.0-release.zip
          unzip dependency-check-1.0.0.0-release.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: dependency-check/bin/dependency-check.sh --project "controlAcademico-web-api" --out . --scan .

      # 8. Construir la aplicación
      - name: Build Application
        run: dotnet build --configuration Release --no-restore
